// src/components/AboutMe.svelte
<script>
  import { onMount } from 'svelte';
  import { fly } from 'svelte/transition';
  import { Cpu, Zap, Globe, Layers } from "lucide-svelte";
  import { Canvas } from '@threlte/core';
  import SectionHeader from "./UI/SectionHeader.svelte";
  import Button from "./UI/Button.svelte";
  import ThreeBackground from "./ThreeBackground.svelte";

  let scrollYProgress = $state(0);
  let sectionRef;

  onMount(() => {
    const handleScroll = () => {
      if (!sectionRef) return;
      const rect = sectionRef.getBoundingClientRect();
      const top = rect.top;
      const height = rect.height;
      const windowHeight = window.innerHeight;
      
      // Rough scrollYProgress equivalent
      let progress = 1 - (top + height) / (height + windowHeight);
      scrollYProgress = Math.max(0, Math.min(1, progress));
    };

    window.addEventListener('scroll', handleScroll);
    return () => window.removeEventListener('scroll', handleScroll);
  });

  let leftY = $derived((scrollYProgress - 0.5) * 100);
  let rightY = $derived(-(scrollYProgress - 0.5) * 100);

  const stats = [
    { label: "Years Experience", value: "3+", sub: "Professional focus" },
    { label: "Successful Projects", value: "50+", sub: "Delivered solutions" },
  ];

  const skillStacks = [
    { icon: Cpu, title: "React / Frontend", tech: "Next.js, Tailwind, Motion" },
    { icon: Layers, title: "Svelte / Modern Web", tech: "SvelteKit, Reactive UI" },
    { icon: Zap, title: "Node.js / Backend", tech: "Express, PostgreSQL, Firebase" },
    { icon: Globe, title: "UI Architecture", tech: "Design Systems, Animations" },
  ];
</script>

<section 
  bind:this={sectionRef} 
  class="py-40 container mx-auto px-6 lg:px-20 relative" 
  id="about"
>
  <!-- Background Placeholder -->
  <div class="absolute inset-0 -z-10 pointer-events-none overflow-hidden opacity-70">
    <div class="absolute inset-0">
      <Canvas>
        <ThreeBackground type="about" />
      </Canvas>
    </div>
  </div>
  
  <SectionHeader 
    subtitle="01 // Profile" 
    title="About Me" 
  />

  <div class="grid lg:grid-cols-2 gap-12 items-start mt-12 perspective-2000">
    <div style:transform="translateY({leftY}px)" class="space-y-6">
      <div class="engineered-border bg-white/[0.02] p-10 relative overflow-hidden transition-all hover:scale-[1.02] active:scale-95">
         <div class="absolute top-0 right-0 p-4 text-[10px] font-mono text-white/5 uppercase tracking-widest">Stack_Catalog</div>
        <h3 class="text-xl font-display font-bold uppercase tracking-wider mb-8">Technical Proficiency</h3>
        <div class="space-y-4">
          {#each skillStacks as stack, i}
            {@const Icon = stack.icon}
            <div class="p-4 border border-white/5 bg-white/[0.01] flex items-center gap-4 group hover:border-primary/30 transition-all hover:translate-x-2">
              <div class="text-primary group-hover:scale-110 transition-transform">
                <Icon size={18} />
              </div>
              <div>
                <div class="text-sm font-bold text-white/80">{stack.title}</div>
                <div class="text-[10px] font-mono text-white/20 uppercase tracking-tighter">{stack.tech}</div>
              </div>
            </div>
          {/each}
        </div>
      </div>

      <div class="grid sm:grid-cols-2 gap-6">
        {#each stats as s}
          <div class="engineered-border bg-white/[0.02] p-8 group hover:border-primary/40 transition-all hover:scale-[1.02]">
            <div class="text-4xl font-display font-black text-primary mb-2 group-hover:scale-110 transition-transform origin-left">{s.value}</div>
            <div class="text-sm font-bold uppercase tracking-wider text-white/80">{s.label}</div>
            <div class="text-[10px] font-mono text-white/20 uppercase mt-1">{s.sub}</div>
          </div>
        {/each}
      </div>
    </div>

    <div style:transform="translateY({rightY}px)" class="relative">
      <div class="relative z-10 space-y-6">
        <p class="text-xl sm:text-2xl font-light text-white/60 leading-relaxed italic">
          "I am Akpe Samuel, popularly known as Rayflix. I build frontend applications that combine robust engineering with engaging user experiences."
        </p>
        <p class="text-white/40 leading-relaxed">
          Based on a passion for technology and creative problem-solving, I collaborate with clients and teams to bring innovative digital ideas to life. I specialize in the modern web ecosystem, focusing on scalability and performance.
        </p>
        
        <div class="pt-8 transition-transform hover:scale-[1.02]">
           <img 
            src="https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?fit=crop&w=500&h=300" 
            alt="Profile" 
            class="w-full h-64 object-cover grayscale opacity-50 hover:grayscale-0 transition-all duration-700 engineered-border"
          />
        </div>
      </div>
      
      <div class="absolute -top-10 -right-10 w-40 h-40 bg-primary/5 rounded-full blur-3xl -z-10"></div>
    </div>
  </div>
</section>

// src/components/AboutMe.tsx
import { motion, useScroll, useTransform } from "motion/react";
import { useRef } from "react";
import { Cpu, Zap, Globe, Layers, Github, Twitter, Linkedin } from "lucide-react";
import { SectionHeader, TiltCard, PerspectiveSection } from "./UI";
import { About3D } from "./SectionBackgrounds";

export function AboutMe() {
  const sectionRef = useRef<HTMLDivElement>(null);
  const { scrollYProgress } = useScroll({
    target: sectionRef,
    offset: ["start end", "end start"]
  });

  const leftY = useTransform(scrollYProgress, [0, 1], [-50, 50]);
  const rightY = useTransform(scrollYProgress, [0, 1], [50, -50]);

  const stats = [
    { label: "Years Experience", value: "3+", sub: "Professional focus" },
    { label: "Successful Projects", value: "50+", sub: "Delivered solutions" },
  ];

  const skillStacks = [
    { icon: <Cpu size={18} />, title: "React / Frontend", tech: "Next.js, Tailwind, Motion" },
    { icon: <Layers size={18} />, title: "Svelte / Modern Web", tech: "SvelteKit, Reactive UI" },
    { icon: <Zap size={18} />, title: "Node.js / Backend", tech: "Express, PostgreSQL, Firebase" },
    { icon: <Globe size={18} />, title: "UI Architecture", tech: "Design Systems, Animations" },
  ];

  return (
    <section ref={sectionRef} className="py-40 container mx-auto px-6 lg:px-20 relative" id="about">
      <About3D />
      <SectionHeader 
        subtitle="01 // Profile" 
        title="About Me" 
      />

      <PerspectiveSection className="grid lg:grid-cols-2 gap-12 items-start mt-12">
        <motion.div style={{ y: leftY }} className="space-y-6">
          <TiltCard className="engineered-border bg-white/[0.02] p-10 relative overflow-hidden">
             <div className="absolute top-0 right-0 p-4 text-[10px] font-mono text-white/5 uppercase tracking-widest">Stack_Catalog</div>
            <h3 className="text-xl font-display font-bold uppercase tracking-wider mb-8">Technical Proficiency</h3>
            <div className="space-y-4">
              {skillStacks.map((stack, i) => (
                <motion.div
                  key={i}
                  whileHover={{ x: 10 }}
                  className="p-4 border border-white/5 bg-white/[0.01] flex items-center gap-4 group hover:border-primary/30 transition-colors"
                >
                  <div className="text-primary group-hover:scale-110 transition-transform">{stack.icon}</div>
                  <div>
                    <div className="text-sm font-bold text-white/80">{stack.title}</div>
                    <div className="text-[10px] font-mono text-white/20 uppercase tracking-tighter">{stack.tech}</div>
                  </div>
                </motion.div>
              ))}
            </div>
          </TiltCard>

          <div className="grid sm:grid-cols-2 gap-6">
            {stats.map((s, i) => (
              <div key={i}>
                <TiltCard className="engineered-border bg-white/[0.02] p-8 group hover:border-primary/40 transition-colors">
                  <div className="text-4xl font-display font-black text-primary mb-2 group-hover:scale-110 transition-transform origin-left">{s.value}</div>
                  <div className="text-sm font-bold uppercase tracking-wider text-white/80">{s.label}</div>
                  <div className="text-[10px] font-mono text-white/20 uppercase mt-1">{s.sub}</div>
                </TiltCard>
              </div>
            ))}
          </div>
        </motion.div>

        <motion.div style={{ y: rightY }} className="relative">
          <div className="relative z-10 space-y-6">
            <p className="text-xl sm:text-2xl font-light text-white/60 leading-relaxed italic">
              "I am Akpe Samuel, popularly known as Rayflix. I build frontend applications that combine robust engineering with engaging user experiences."
            </p>
            <p className="text-white/40 leading-relaxed">
              Based on a passion for technology and creative problem-solving, I collaborate with clients and teams to bring innovative digital ideas to life. I specialize in the modern web ecosystem, focusing on scalability and performance.
            </p>
            
            <TiltCard className="pt-8">
               <img 
                src="https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?fit=crop&w=500&h=300" 
                alt="Profile" 
                className="w-full h-64 object-cover grayscale opacity-50 hover:grayscale-0 transition-all duration-700 engineered-border"
              />
            </TiltCard>
          </div>
          
          {/* Decorative Elements */}
          <div className="absolute -top-10 -right-10 w-40 h-40 bg-primary/5 rounded-full blur-3xl -z-10" />
        </motion.div>
      </PerspectiveSection>
    </section>
  );
}
